# docker run --d --rm  --name mongo1 -p 27017:27017 -v mongodbdata:/data/db mongo

version: "3.0"

services:
  mongo:
    image: mongo
    container_name: mongo1
    ports:  
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata: